name: Coverage Reporting

on:
  push:
    branches:
      - master
      - develop

  pull_request:
    branches:
      - '**'

jobs:

  coverageReport:
    strategy:
      matrix:
        api-level: [21, 21] 
      fail-fast: false
    runs-on: macOS-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: create instrumentation coverage
        uses: ReactiveCircus/android-emulator-runner@v2.8.0
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          script: bash contrib/instrumentation.sh

      - name: Upload screenshot result
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: ${{ matrix.api-level }}
          path: screencap.png

      - name: create unit coverage 2
        run: ./gradlew jacocoTestCustomExampleDebugUnitTestReport

      - name: create unit coverage
        run: ./gradlew jacocoTestDebugUnitTestReport


      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          verbose: true
